package LLD.ATMMachine.ATM_StateDesignPattern.State;

import LLD.ATMMachine.ATM_StateDesignPattern.API.BackendAPIInterface;
import LLD.ATMMachine.ATM_StateDesignPattern.API.BackendAPIV1;
import LLD.ATMMachine.ATM_StateDesignPattern.DTO.CreateTransactionRequestDTO;
import LLD.ATMMachine.ATM_StateDesignPattern.Enums.ATMStates;
import LLD.ATMMachine.ATM_StateDesignPattern.Model.ATM;
import LLD.ATMMachine.ATM_StateDesignPattern.Model.Card;

public class ReadyForTransactionState implements State{

    /*
        When we are in out ready state , the only that should happen in the initialization of a transaction
        example: we cannot withdraw cast in the ready state
     */

    private final ATM atm;
    private final BackendAPIInterface atmBackendAPI;


    /*
        The Ready state is the initial state of the ATM
        we need an ATM object to get the ATM id which will be used to generate a transaction id
     */

    public ReadyForTransactionState(ATM atm) {
        this.atm = atm;
        this.atmBackendAPI = new BackendAPIV1();
    }


    @Override
    public int initTransaction() {
        System.out.println("Transaction Initiated");
        /*
            This method will return a transaction id which will be used to track the transaction
            The transaction id will be generated by the corresponding backend service i.e. the banking API
            eg -> AXIS Bank ATM will call the AXIS Bank API to generate a transaction id and return it to the ATM

            Details/Data we will be sending to the API
            1. ATM ID

         */
        CreateTransactionRequestDTO createTransactionDTO = new CreateTransactionRequestDTO(this.atm.getAtmId());

        int transactionId = this.atmBackendAPI.createTransaction(createTransactionDTO);

        if(transactionId==0){
            throw new IllegalStateException("Transaction Id cannot be created");
        }

        /*
         Now as we have the txnId we should move the ATM to the next state i.e. ReadCardDetailsState
         so this will call a API for changing the state of the ATM to ReadCardDetailsState

         So to migrate the ATM states we need to do 2 things :

         1. Checking the current state of the ATM and if it is in the ReadyForTransactionState then
            we can move to the next state i.e. ReadCardDetailsState
         2. Call the backend API for updating the state of the ATM to ReadCardDetailsState

         The Atm class will be responsible for changing the state of the ATM to ReadCardDetailsState

         */

        this.atm.changeState(new ReadCardDetailsState(this.atm));

        return transactionId;

    }

    @Override
    public boolean readCardDetails(Card card , int pin) {
        throw new IllegalStateException("Cannot read card details without initializing transaction");
    }

    @Override
    public int dispenseCash(Card card , double amount, int transactionId) {
        throw new IllegalStateException("Cannot dispense cash without reading card details");
    }

    @Override
    public void ejectCard() {
        throw new IllegalStateException("Cannot eject card without reading card details");
    }

    @Override
    public boolean readCashWithdrawlDetails(Card card , int transactionId, double amount) {
        throw new IllegalStateException("Cannot read cash withdrawl details without card details");
    }

    @Override
    public ATMStates getState() {
        return ATMStates.READY_FOR_TRANSACTION;
    }

    @Override
    public boolean cancelTransaction(int transactionId) {
        throw new IllegalStateException("Cannot cancel a transaction without reading a card");
    }
}
